project:
  type: website

website:
  title: "LF11a"
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
      - href: 01_Willkommen_Struktur.qmd
        text: 01 Willkommen zu LF11a - Themen und Zeitplan
      - href: 02b_OOP_Escape-Room.qmd
        text: 02b OOP Escape Room

format:
  revealjs:
    embed-resources: true
    profile: public
    include-after-body: libs/backlink.html
    css: libs/styles.css
    logo: libs/_Images/logo-AFBB.svg

profiles:
  internal:
    # zum Zeigen, mit Bildern
  public:
    # zum Veröffentlichen, ohne manche Bilder

publish:
  gh-pages: true

